add_rules("mode.debug", "mode.release")
add_languages("c++20")
target("coc")
    add_toolchains("clang")
    set_kind("binary")
    set_targetdir("target/")
    add_files("src/*.ixx")
    add_files("src/*.cc")